version: '3.8'

# 开发环境配置
services:
  mysql:
    image: mysql:8.0
    container_name: mall-mysql-dev
    volumes:
      - mysql-data-dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-zhx123456}
      - MYSQL_DATABASE=shop
      # 添加MySQL初始化参数
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    profiles:
      - default

  mall-server:
    container_name: mall-server-dev
    build:
      context: ./mall-server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - PORT=8080
      - DEBUG=app:*
      - DB_NAME=shop
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_PASSWORD:-zhx123456}
      - API_PREFIX=/api
      - LOG_LEVEL=debug
      - ENABLE_MOCK=true
    volumes:
      - ./mall-server:/app
      - /app/node_modules
    profiles:
      - default
      - no-mysql
    # 使用Dockerfile中的默认命令

  mall-admin:
    container_name: mall-admin-dev
    build:
      context: ./mall-admin
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=development
    environment:
      - VITE_API_URL=http://localhost:8081
      - VITE_USE_MOCK=true
      - VITE_USE_DEVTOOLS=true
    profiles:
      - default
      - no-mysql

volumes:
  mysql-data-dev: 