version: '3.8'

# 生产环境配置
services:
  mysql:
    image: mysql:8.0
    container_name: mall-mysql-prod
    volumes:
      - mysql-data-prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zhx123456
      - MYSQL_DATABASE=shop
    restart: always
    # 生产环境数据库安全配置
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"

  mall-server:
    container_name: mall-server-prod
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=shop
      - DB_USER=root
      - DB_PASSWORD=123456
      - API_PREFIX=/api
      - LOG_LEVEL=error
      - ENABLE_MOCK=false
      - JWT_SECRET=${JWT_SECRET:-secure_production_jwt_secret}
    restart: always
    # 生产环境健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mall-admin:
    container_name: mall-admin-prod
    build:
      context: ./mall-admin
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=production
    environment:
      - VITE_API_URL=http://api.example.com
      - VITE_USE_MOCK=false
      - VITE_USE_DEVTOOLS=false
    restart: always
    # 生产环境健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql-data-prod: 