version: '3.8'

# 测试环境配置
services:
  mysql:
    container_name: mall-mysql-test
    volumes:
      - mysql-data-test:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zhx199710085470
      - MYSQL_DATABASE=shop

  mall-server:
    container_name: mall-server-test
    environment:
      - NODE_ENV=testing
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=shop
      - DB_USER=root
      - DB_PASSWORD=zhx199710085470
      - API_PREFIX=/api
      - LOG_LEVEL=info
      - ENABLE_MOCK=false
      - JWT_SECRET=testing_jwt_secret_key

  mall-admin:
    container_name: mall-admin-test
    build:
      args:
        - BUILD_MODE=testing
    environment:
      - VITE_API_URL=http://test-api.example.com
      - VITE_USE_MOCK=false
      - VITE_USE_DEVTOOLS=true

volumes:
  mysql-data-test: 